image: Visual Studio 2022

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/
    - /bugfix/.*/

environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable --version 5.10.3 -y

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Execution.Forked.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true
  project: source/Jobbr.Execution.Forked.sln

test_script:
  - vstest.console /logger:Appveyor "C:\projects\jobbr-execution-forked\source\Jobbr.Server.ForkedExecution.Tests\bin\Release\net6.0\Jobbr.Server.ForkedExecution.Tests.dll" "C:\projects\jobbr-execution-forked\source\submodules\jobbr-runtime\source\Jobbr.Runtime.Tests\bin\Release\net6.0\Jobbr.Runtime.Tests.dll"

after_build:
  - cmd: nuget pack source\Jobbr.Execution.Forked.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack source\Jobbr.Runtime.ForkedExecution.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.Execution.Forked.%GitVersion_SemVer%.nupkg"
  - cmd: appveyor PushArtifact "Jobbr.Runtime.ForkedExecution.%GitVersion_SemVer%.nupkg"

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: 60SMVZkhtzWAeH6Mp7DT1YZlZGGG8jwOEXMH0oRhX1iQLBejg1TpaDxgN6i0RisX
    on:
      appveyor_repo_tag: true
